title: welcome to my blog
author: Adel Altuwaijri
email: adel@adelaltuwaijri.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome, Here I am writing some thoughts and tips that I learned through my work on machine learning projects.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  AdelAltuwaijri # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
